### ISSUE TITLE
Delivery order to dpd

### ISSUE THREAD

**Issue by god1dog** [retailcrm/api-client-go#33]
I can not fill in the fields for dpd delivery:
Fields **locked**, **selfPickup**, **payerType** not in api and golang types
Field **deliveryType** not in golang types

**Comment by Neur0toxine** [comment]
Hello!

Can you please elaborate how exactly you want to use these fields you marked as nonexistent in the API? It'll be easier to solve this issue with this information.

Also, about `deliveryType` field - we wil add it in the next release.

Thanks!

**Comment by god1dog** [comment]
По описанию https://help.retailcrm.ru/delivery_data_ru.html эти поля я могу только получить, но изменять я их могу только из интерфейса но мне нужно полное взаимодействие с API
locked bool Не отправлять данные в службу доставки 
selfPickup bool Самопривоз на терминал 
payerType string Плательщик за доставку (sender, receiver)

Плюс если указать
order[delivery][data][tariff]="PCL"
order[delivery][data][pickuppointId]="168H"
то нужный мне тариф не выбирается (в интерфейсе тариф могу изменить)

**Comment by gwinn** [comment]
Для конкретных доставок структуры в библиотеке не заводились и вероятнее всего не будут, только общие поля. В целом можно самостоятельно в рамках вашего проекта добавить недостающие структуры и использовать их совместно с библиотекой, относительно доступности полей на редактирование - https://help.retailcrm.ru/delivery_data_ru.html, то тут pickuppointId доступен для редактирования, tariffName только на чтение

payerType в библиотеке есть, selfPickup и locked рассмотрим на добавление

**Comment by god1dog** [comment]
Сейчас отправляю через ваш клиент свою структуру доставки. 
На счет структуры конкретной доставки вижу что вы отказались заводить тип для dpd давайте хоть изменим OrderDeliveryData на interface{} (решение конечно костыльное) но как с данными доставки взаимодействовать если это будет отдельное подключение то и смысла в методе createOrder() нет с точки зрения консистентности данных

Просто заметил что у вас дока сырая по dpd. 
1. _tariffName только на чтение_ в данный момент использую не документированное поле deliveryCode (в доке оно именуется tariff но с ним у меня не работает выбор тарифа)
1. Поле payerType не хочет работать со значениями sender, receiver значение подставляется всегда по умолчанию из настроек dpd

**Comment by Neur0toxine** [comment]
В новой версии проблема решена. Тип поля с данными доставки не поменялся, но добавлена возможность добавления любых кастомных полей в это поле. Базовые данные доставки находятся в структуре `OrderDeliveryDataBasic`, которая включена в `OrderDeliveryData`. В `OrderDeliveryData` добавлено поле `AdditionalFields` с типом `map[string]interface{}`. Все значения, добавленные в `AdditionalData` в результате маршалинга окажутся в данных доставки.

Пример:
```go
OrderDeliveryData{
	OrderDeliveryDataBasic: OrderDeliveryDataBasic{
		TrackNumber: "track",
        },
	AdditionalFields: map[string]interface{}{
		"locked": true,
	},
}
```
после маршалинга превратится в JSON следующего вида
```json
{
  "locked": true,
  "trackNumber": "track"
}
```

Это работает и в обратную сторону, т.е. демаршалинг JSON'а выше даст ровно ту же структуру, из которой получился данный JSON.
